### ISSUE TITLE
Could not find or load main class com.vaadin.buildhelpers.CompileTheme

### ISSUE THREAD

**Issue by dsalychev** [Saulis/vaadin-idea-workspace#1]
I'm at the end of 5 "Add modules".

OS: `3.16.7 x86_64 GNU/Linux`
JDK: `1.7.0_75`
IDEA: `14.1.4 Build 141.1532`

I received this error while executing vaadin/build/ide.xml within IntelliJ IDEA. This is a part of IDE log:

```
Error: Could not find or load main class com.vaadin.buildhelpers.CompileTheme
/home/dsalychev/git/vaadin/build/ide.xml:105: Java returned: 1
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:453)
    at java.lang.Thread.run(Thread.java:745)
```

I understood that my classpath doesn't contain `com.vaadin.buildhelpers.CompileTheme`, but I have no idea how to fix it at the moment. Any thoughts?

**Comment by dsalychev** [comment]
There is a [full log](https://gist.github.com/dsalychev/f73ddaef773ec31c60d9) from IDE.
